quarkus:
  datasource:
    db-kind: mysql
    username: root
    password: lipi
    jdbc:
      url: jdbc:mysql://localhost:3306/agondb
      driver: com.mysql.cj.jdbc.Driver

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: 0.0.11
    baseline-description: Versão inicial do DB
    validate-on-migrate: true
    schemas: agondb
    table: flyway_quarkus_history
    locations: db/migration

cargoProxy/mp-rest/uri: http://localhost:8080/agon/empresas/cargos
cargoProxy/mp-rest/scope: javax.inject.Singleton
enderecoProxy/mp-rest: http://localhost:8080/agon/enderecos
enderecoProxy/scope: javax.inject.Singleton
funcionarioProxy/mp-rest/uri: http://localhost:8080/agon/empresas/funcionarios
funcionarioProxy/mp-rest/scope: javax.inject.Singleton
usuarioProxy/mp-rest/uri: http://localhost:8080/agon/usuarios
usuarioProxy/mp-rest/scope: javax.inject.Singleton
telefoneProxy/mp-rest/uri: http://localhost:8080/agon/telefones
telefoneProxy/scope: javax.inject.Singleton

"%dev":
  quarkus:
    http:
      root-path: /agon
      port: 8080



