quarkus:
  datasource:
    db-kind: mysql
    username: root
    password: lipi
    jdbc:
      url: jdbc:mysql://localhost:3306/agondb
      driver: com.mysql.cj.jdbc.Driver

  http:
    root-path: /agon
    port: 8080

  flyway:
    migrate-at-start: false
    baseline-on-migrate: false
    baseline-version: 0.0.11
    baseline-description: Versão inicial do DB
    validate-on-migrate: false
    schemas:
      agondb
    table:
      flyway_quarkus_history
    locations:
      db/migration

cargoProxy:
  mp-rest:
    uri:
      http://localhost:8080/agon/api/empresas/cargos
    scope:
      javax.inject.Singleton

enderecoProxy:
  mp-rest:
    uri:
      http://localhost:8080/agon/enderecos
    scope:
      javax.inject.Singleton

funcionarioProxy:
  mp-rest:
    uri:
      http://localhost:8080/agon/api/empresas/funcionarios
    scope:
      javax.inject.Singleton

telefoneProxy:
  mp-rest:
    uri:
      http://localhost:8080/agon/api/telefones
    scope:
      javax.inject.Singleton

usuarioProxy:
  mp-rest:
    uri:
      http://localhost:8080/agon/api/usuarios
    scope:
      javax.inject.Singleton

